// <auto-generated />
using DietPlanner.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DietPlanner.Migrations
{
    [DbContext(typeof(DietContext))]
    [Migration("20251029212545_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DietPlanner.Models.Food", b =>
                {
                    b.Property<int>("FoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("food_id");

                    b.Property<string>("Allergen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Calories")
                        .HasColumnType("REAL");

                    b.Property<double>("Carbs")
                        .HasColumnType("REAL");

                    b.Property<double>("Fat")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Protein")
                        .HasColumnType("REAL");

                    b.HasKey("FoodId");

                    b.ToTable("Foods");

                    b.HasData(
                        new
                        {
                            FoodId = 1,
                            Allergen = "None",
                            Calories = 52.0,
                            Carbs = 14.0,
                            Fat = 0.20000000000000001,
                            Name = "Μήλο",
                            Protein = 0.29999999999999999
                        },
                        new
                        {
                            FoodId = 2,
                            Allergen = "None",
                            Calories = 89.0,
                            Carbs = 23.0,
                            Fat = 0.29999999999999999,
                            Name = "Μπανάνα",
                            Protein = 1.1000000000000001
                        },
                        new
                        {
                            FoodId = 3,
                            Allergen = "None",
                            Calories = 165.0,
                            Carbs = 0.0,
                            Fat = 3.6000000000000001,
                            Name = "Στήθος Κοτόπουλο",
                            Protein = 31.0
                        },
                        new
                        {
                            FoodId = 4,
                            Allergen = "Fish",
                            Calories = 208.0,
                            Carbs = 0.0,
                            Fat = 13.0,
                            Name = "Σολομός",
                            Protein = 20.0
                        },
                        new
                        {
                            FoodId = 5,
                            Allergen = "None",
                            Calories = 55.0,
                            Carbs = 11.0,
                            Fat = 0.59999999999999998,
                            Name = "Μπρόκολο",
                            Protein = 3.7000000000000002
                        },
                        new
                        {
                            FoodId = 6,
                            Allergen = "None",
                            Calories = 111.0,
                            Carbs = 23.0,
                            Fat = 0.90000000000000002,
                            Name = "Ρύζι καστανό",
                            Protein = 2.6000000000000001
                        },
                        new
                        {
                            FoodId = 7,
                            Allergen = "Nuts",
                            Calories = 579.0,
                            Carbs = 22.0,
                            Fat = 49.0,
                            Name = "Αμύγδαλα",
                            Protein = 21.0
                        },
                        new
                        {
                            FoodId = 8,
                            Allergen = "Dairy",
                            Calories = 73.0,
                            Carbs = 3.6000000000000001,
                            Fat = 2.0,
                            Name = "Γιαούρτι Στραγγιστό 2%",
                            Protein = 10.0
                        },
                        new
                        {
                            FoodId = 9,
                            Allergen = "Egg",
                            Calories = 155.0,
                            Carbs = 1.1000000000000001,
                            Fat = 11.0,
                            Name = "Αυγό",
                            Protein = 13.0
                        },
                        new
                        {
                            FoodId = 10,
                            Allergen = "None",
                            Calories = 23.0,
                            Carbs = 3.6000000000000001,
                            Fat = 0.40000000000000002,
                            Name = "Σπανάκι",
                            Protein = 2.8999999999999999
                        },
                        new
                        {
                            FoodId = 11,
                            Allergen = "None",
                            Calories = 86.0,
                            Carbs = 20.0,
                            Fat = 0.10000000000000001,
                            Name = "Γλυκοπατάτα",
                            Protein = 1.6000000000000001
                        },
                        new
                        {
                            FoodId = 12,
                            Allergen = "None",
                            Calories = 884.0,
                            Carbs = 0.0,
                            Fat = 100.0,
                            Name = "Ελαιόλαδο",
                            Protein = 0.0
                        },
                        new
                        {
                            FoodId = 13,
                            Allergen = "Gluten",
                            Calories = 389.0,
                            Carbs = 66.299999999999997,
                            Fat = 6.9000000000000004,
                            Name = "Βρώμη",
                            Protein = 16.899999999999999
                        },
                        new
                        {
                            FoodId = 14,
                            Allergen = "None",
                            Calories = 116.0,
                            Carbs = 20.0,
                            Fat = 0.40000000000000002,
                            Name = "Φακές",
                            Protein = 9.0
                        },
                        new
                        {
                            FoodId = 15,
                            Allergen = "Fish",
                            Calories = 132.0,
                            Carbs = 0.0,
                            Fat = 1.3,
                            Name = "Τόνος σε νερό",
                            Protein = 28.0
                        },
                        new
                        {
                            FoodId = 16,
                            Allergen = "None",
                            Calories = 15.0,
                            Carbs = 3.6000000000000001,
                            Fat = 0.10000000000000001,
                            Name = "Αγγούρι",
                            Protein = 0.69999999999999996
                        },
                        new
                        {
                            FoodId = 17,
                            Allergen = "None",
                            Calories = 18.0,
                            Carbs = 3.8999999999999999,
                            Fat = 0.20000000000000001,
                            Name = "Ντομάτα",
                            Protein = 0.90000000000000002
                        },
                        new
                        {
                            FoodId = 18,
                            Allergen = "None",
                            Calories = 217.0,
                            Carbs = 0.0,
                            Fat = 15.0,
                            Name = "Μοσχαρίσιος Κιμάς (90/10)",
                            Protein = 19.0
                        },
                        new
                        {
                            FoodId = 19,
                            Allergen = "None",
                            Calories = 120.0,
                            Carbs = 21.0,
                            Fat = 1.8999999999999999,
                            Name = "Κινόα",
                            Protein = 4.4000000000000004
                        },
                        new
                        {
                            FoodId = 20,
                            Allergen = "None",
                            Calories = 32.0,
                            Carbs = 7.7000000000000002,
                            Fat = 0.29999999999999999,
                            Name = "Φράουλες",
                            Protein = 0.69999999999999996
                        },
                        new
                        {
                            FoodId = 21,
                            Allergen = "None",
                            Calories = 160.0,
                            Carbs = 9.0,
                            Fat = 15.0,
                            Name = "Αβοκάντο",
                            Protein = 2.0
                        },
                        new
                        {
                            FoodId = 22,
                            Allergen = "Dairy",
                            Calories = 98.0,
                            Carbs = 3.3999999999999999,
                            Fat = 4.2999999999999998,
                            Name = "Τυρί Cottage",
                            Protein = 11.0
                        },
                        new
                        {
                            FoodId = 23,
                            Allergen = "Gluten",
                            Calories = 247.0,
                            Carbs = 41.0,
                            Fat = 3.3999999999999999,
                            Name = "Ψωμί ολικής άλεσης",
                            Protein = 13.0
                        },
                        new
                        {
                            FoodId = 24,
                            Allergen = "None",
                            Calories = 135.0,
                            Carbs = 0.0,
                            Fat = 1.0,
                            Name = "Γαλοπούλα βραστή",
                            Protein = 29.0
                        },
                        new
                        {
                            FoodId = 25,
                            Allergen = "None",
                            Calories = 164.0,
                            Carbs = 27.0,
                            Fat = 2.6000000000000001,
                            Name = "Ρεβύθια",
                            Protein = 8.9000000000000004
                        },
                        new
                        {
                            FoodId = 26,
                            Allergen = "None",
                            Calories = 31.0,
                            Carbs = 6.0,
                            Fat = 0.29999999999999999,
                            Name = "Πιπεριά Κόκκινη",
                            Protein = 1.0
                        },
                        new
                        {
                            FoodId = 27,
                            Allergen = "None",
                            Calories = 304.0,
                            Carbs = 82.0,
                            Fat = 0.0,
                            Name = "Μέλι",
                            Protein = 0.29999999999999999
                        },
                        new
                        {
                            FoodId = 28,
                            Allergen = "Nuts",
                            Calories = 588.0,
                            Carbs = 20.0,
                            Fat = 50.0,
                            Name = "Φυστικοβούτυρο",
                            Protein = 25.0
                        },
                        new
                        {
                            FoodId = 29,
                            Allergen = "Dairy",
                            Calories = 47.0,
                            Carbs = 5.0,
                            Fat = 1.5,
                            Name = "Γάλα 1.5%",
                            Protein = 3.3999999999999999
                        },
                        new
                        {
                            FoodId = 30,
                            Allergen = "None",
                            Calories = 57.0,
                            Carbs = 14.0,
                            Fat = 0.29999999999999999,
                            Name = "Μύρτιλα (Blueberries)",
                            Protein = 0.69999999999999996
                        });
                });

            modelBuilder.Entity("DietPlanner.Models.Meal", b =>
                {
                    b.Property<int>("MealId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("meal_id");

                    b.Property<int>("MealType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("meal_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MealId");

                    b.ToTable("Meals");

                    b.HasData(
                        new
                        {
                            MealId = 1,
                            MealType = 0,
                            Name = "Πρωινό με Βρώμη & Φρούτα"
                        },
                        new
                        {
                            MealId = 2,
                            MealType = 2,
                            Name = "Μεσημεριανό με Κοτόπουλο & Κινόα"
                        },
                        new
                        {
                            MealId = 3,
                            MealType = 4,
                            Name = "Βραδινό με Σολομό & Γλυκοπατάτα"
                        },
                        new
                        {
                            MealId = 4,
                            MealType = 3,
                            Name = "Γιαούρτι με Μέλι & Ξηρούς Καρπούς"
                        },
                        new
                        {
                            MealId = 5,
                            MealType = 0,
                            Name = "Ομελέτα με Σπανάκι"
                        },
                        new
                        {
                            MealId = 6,
                            MealType = 2,
                            Name = "Σαλάτα με Τόνο"
                        },
                        new
                        {
                            MealId = 7,
                            MealType = 1,
                            Name = "Τοστ με Γαλοπούλα & Αβοκάντο"
                        },
                        new
                        {
                            MealId = 8,
                            MealType = 2,
                            Name = "Κιμάς με Ρύζι"
                        },
                        new
                        {
                            MealId = 9,
                            MealType = 0,
                            Name = "Smoothie Πρωτεΐνης"
                        },
                        new
                        {
                            MealId = 10,
                            MealType = 4,
                            Name = "Σαλάτα με Ρεβύθια"
                        },
                        new
                        {
                            MealId = 11,
                            MealType = 3,
                            Name = "Cottage με Φράουλες"
                        },
                        new
                        {
                            MealId = 12,
                            MealType = 2,
                            Name = "Φακές Σούπα"
                        });
                });

            modelBuilder.Entity("DietPlanner.Models.MealContent", b =>
                {
                    b.Property<int>("MealId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("meal_id");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("food_id");

                    b.Property<double>("QuantityGrams")
                        .HasColumnType("REAL")
                        .HasColumnName("quantity_grams");

                    b.HasKey("MealId", "FoodId");

                    b.HasIndex("FoodId");

                    b.ToTable("Meal_Foods");

                    b.HasData(
                        new
                        {
                            MealId = 1,
                            FoodId = 13,
                            QuantityGrams = 50.0
                        },
                        new
                        {
                            MealId = 1,
                            FoodId = 2,
                            QuantityGrams = 100.0
                        },
                        new
                        {
                            MealId = 1,
                            FoodId = 7,
                            QuantityGrams = 15.0
                        },
                        new
                        {
                            MealId = 1,
                            FoodId = 29,
                            QuantityGrams = 150.0
                        },
                        new
                        {
                            MealId = 2,
                            FoodId = 3,
                            QuantityGrams = 150.0
                        },
                        new
                        {
                            MealId = 2,
                            FoodId = 19,
                            QuantityGrams = 180.0
                        },
                        new
                        {
                            MealId = 2,
                            FoodId = 26,
                            QuantityGrams = 100.0
                        },
                        new
                        {
                            MealId = 2,
                            FoodId = 12,
                            QuantityGrams = 10.0
                        },
                        new
                        {
                            MealId = 3,
                            FoodId = 4,
                            QuantityGrams = 150.0
                        },
                        new
                        {
                            MealId = 3,
                            FoodId = 11,
                            QuantityGrams = 200.0
                        },
                        new
                        {
                            MealId = 3,
                            FoodId = 10,
                            QuantityGrams = 150.0
                        },
                        new
                        {
                            MealId = 4,
                            FoodId = 8,
                            QuantityGrams = 200.0
                        },
                        new
                        {
                            MealId = 4,
                            FoodId = 27,
                            QuantityGrams = 15.0
                        },
                        new
                        {
                            MealId = 4,
                            FoodId = 7,
                            QuantityGrams = 20.0
                        },
                        new
                        {
                            MealId = 5,
                            FoodId = 9,
                            QuantityGrams = 120.0
                        },
                        new
                        {
                            MealId = 5,
                            FoodId = 10,
                            QuantityGrams = 70.0
                        },
                        new
                        {
                            MealId = 5,
                            FoodId = 12,
                            QuantityGrams = 5.0
                        },
                        new
                        {
                            MealId = 6,
                            FoodId = 15,
                            QuantityGrams = 100.0
                        },
                        new
                        {
                            MealId = 6,
                            FoodId = 17,
                            QuantityGrams = 150.0
                        },
                        new
                        {
                            MealId = 6,
                            FoodId = 16,
                            QuantityGrams = 100.0
                        },
                        new
                        {
                            MealId = 6,
                            FoodId = 12,
                            QuantityGrams = 15.0
                        },
                        new
                        {
                            MealId = 7,
                            FoodId = 23,
                            QuantityGrams = 70.0
                        },
                        new
                        {
                            MealId = 7,
                            FoodId = 24,
                            QuantityGrams = 60.0
                        },
                        new
                        {
                            MealId = 7,
                            FoodId = 21,
                            QuantityGrams = 50.0
                        },
                        new
                        {
                            MealId = 8,
                            FoodId = 18,
                            QuantityGrams = 150.0
                        },
                        new
                        {
                            MealId = 8,
                            FoodId = 6,
                            QuantityGrams = 200.0
                        },
                        new
                        {
                            MealId = 8,
                            FoodId = 17,
                            QuantityGrams = 100.0
                        },
                        new
                        {
                            MealId = 9,
                            FoodId = 29,
                            QuantityGrams = 250.0
                        },
                        new
                        {
                            MealId = 9,
                            FoodId = 8,
                            QuantityGrams = 100.0
                        },
                        new
                        {
                            MealId = 9,
                            FoodId = 20,
                            QuantityGrams = 50.0
                        },
                        new
                        {
                            MealId = 9,
                            FoodId = 28,
                            QuantityGrams = 20.0
                        },
                        new
                        {
                            MealId = 10,
                            FoodId = 25,
                            QuantityGrams = 150.0
                        },
                        new
                        {
                            MealId = 10,
                            FoodId = 16,
                            QuantityGrams = 100.0
                        },
                        new
                        {
                            MealId = 10,
                            FoodId = 17,
                            QuantityGrams = 100.0
                        },
                        new
                        {
                            MealId = 10,
                            FoodId = 26,
                            QuantityGrams = 50.0
                        },
                        new
                        {
                            MealId = 10,
                            FoodId = 12,
                            QuantityGrams = 20.0
                        },
                        new
                        {
                            MealId = 11,
                            FoodId = 22,
                            QuantityGrams = 150.0
                        },
                        new
                        {
                            MealId = 11,
                            FoodId = 20,
                            QuantityGrams = 100.0
                        },
                        new
                        {
                            MealId = 11,
                            FoodId = 30,
                            QuantityGrams = 50.0
                        },
                        new
                        {
                            MealId = 12,
                            FoodId = 14,
                            QuantityGrams = 250.0
                        },
                        new
                        {
                            MealId = 12,
                            FoodId = 12,
                            QuantityGrams = 10.0
                        });
                });

            modelBuilder.Entity("DietPlanner.Models.MealContent", b =>
                {
                    b.HasOne("DietPlanner.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DietPlanner.Models.Meal", "Meal")
                        .WithMany()
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });
#pragma warning restore 612, 618
        }
    }
}
