using DietPlanner.Models;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DietPlanner.DataAccess
{
    public static class MealSeeder
    {
        public static void Seed(EntityTypeBuilder<Meal> builder)
        {
            builder.HasData(
                new Meal { MealId = 1, Name = "Oatmeal & Fruit Breakfast", MealType = MealType.Breakfast },
                new Meal { MealId = 2, Name = "Chicken & Quinoa Lunch", MealType = MealType.Lunch },
                new Meal { MealId = 3, Name = "Salmon & Sweet Potato Dinner", MealType = MealType.Dinner },
                new Meal { MealId = 4, Name = "Yogurt with Honey & Nuts", MealType = MealType.AfternoonSnack },
                new Meal { MealId = 5, Name = "Spinach Omelette", MealType = MealType.Breakfast },
                new Meal { MealId = 6, Name = "Tuna Salad", MealType = MealType.Lunch },
                new Meal { MealId = 7, Name = "Turkey & Avocado Toast", MealType = MealType.MorningSnack },
                new Meal { MealId = 8, Name = "Minced Meat with Rice", MealType = MealType.Lunch },
                new Meal { MealId = 9, Name = "Protein Smoothie", MealType = MealType.Breakfast },
                new Meal { MealId = 10, Name = "Chickpea Salad", MealType = MealType.Dinner },
                new Meal { MealId = 11, Name = "Cottage Cheese with Strawberries", MealType = MealType.AfternoonSnack },
                new Meal { MealId = 12, Name = "Lentil Soup", MealType = MealType.Lunch },
                new Meal { MealId = 13, Name = "Greek Yogurt Parfait", MealType = MealType.Breakfast },
                new Meal { MealId = 14, Name = "Black Bean Burrito Bowl", MealType = MealType.Lunch },
                new Meal { MealId = 15, Name = "Tofu Stir-Fry", MealType = MealType.Dinner },
                new Meal { MealId = 16, Name = "Edamame Snack", MealType = MealType.MorningSnack },
                new Meal { MealId = 17, Name = "Shrimp & Veggie Skewers", MealType = MealType.Dinner },
                new Meal { MealId = 18, Name = "Pork Loin & Sweet Potato", MealType = MealType.Dinner },
                new Meal { MealId = 19, Name = "Whole Wheat Pasta Primavera", MealType = MealType.Lunch },
                new Meal { MealId = 20, Name = "Hummus & Veggies", MealType = MealType.AfternoonSnack },
                new Meal { MealId = 21, Name = "Walnut & Spinach Salad", MealType = MealType.Lunch },
                new Meal { MealId = 22, Name = "Pumpkin Seed Oatmeal", MealType = MealType.Breakfast },
                new Meal { MealId = 23, Name = "Pear & Cottage Cheese", MealType = MealType.MorningSnack },
                new Meal { MealId = 24, Name = "Kefir Berry Smoothie", MealType = MealType.Breakfast },
                new Meal { MealId = 25, Name = "Tempeh Buddha Bowl", MealType = MealType.Lunch },
                new Meal { MealId = 26, Name = "Sardine Toast", MealType = MealType.MorningSnack },
                new Meal { MealId = 27, Name = "Oat Milk Protein Shake", MealType = MealType.Breakfast },
                new Meal { MealId = 28, Name = "Cauliflower Fried Rice (Vegan)", MealType = MealType.Lunch },
                new Meal { MealId = 29, Name = "Corn & Black Bean Salad", MealType = MealType.Dinner },
                new Meal { MealId = 30, Name = "Dark Chocolate & Almonds", MealType = MealType.AfternoonSnack },
                new Meal { MealId = 31, Name = "Chia Pudding with Berries", MealType = MealType.Breakfast },
                new Meal { MealId = 32, Name = "Grilled Beef & Veggies", MealType = MealType.Dinner },

                // New Low-Fat Meals
                new Meal { MealId = 33, Name = "Simple Fruit Salad", MealType = MealType.Breakfast },
                new Meal { MealId = 34, Name = "Lean Turkey Salad", MealType = MealType.Lunch },
                new Meal { MealId = 35, Name = "Steamed Salmon & Broccoli", MealType = MealType.Dinner },
                new Meal { MealId = 36, Name = "Hummus on Wholemeal Bread", MealType = MealType.MorningSnack },
                new Meal { MealId = 37, Name = "Greek Yogurt with Berries", MealType = MealType.AfternoonSnack },

                new Meal { MealId = 38, Name = "Chicken and Vegetable Stir-fry", MealType = MealType.Dinner },
                new Meal { MealId = 39, Name = "Hearty Beef and Vegetable Stew", MealType = MealType.Dinner },
                new Meal { MealId = 40, Name = "Scrambled Eggs with Spinach and Toast", MealType = MealType.Breakfast },
                new Meal { MealId = 41, Name = "Quinoa Salad with Chickpeas and Veggies", MealType = MealType.Lunch },
                new Meal { MealId = 42, Name = "Turkey Meatballs with Whole Wheat Pasta", MealType = MealType.Dinner },
                new Meal { MealId = 43, Name = "Apple Slices with Peanut Butter", MealType = MealType.AfternoonSnack },
                new Meal { MealId = 44, Name = "Hard-Boiled Eggs", MealType = MealType.MorningSnack },
                new Meal { MealId = 45, Name = "Chicken Salad Sandwich", MealType = MealType.Lunch },
                new Meal { MealId = 46, Name = "Baked Salmon with Roasted Potatoes and Carrots", MealType = MealType.Dinner },
                new Meal { MealId = 47, Name = "Overnight Oats with Berries", MealType = MealType.Breakfast },
                new Meal { MealId = 48, Name = "Simple Chicken and Rice", MealType = MealType.Lunch },

                // 30 New Meals
                new Meal { MealId = 49, Name = "Tofu Scramble", MealType = MealType.Breakfast },
                new Meal { MealId = 50, Name = "Cottage Cheese with Pear and Almonds", MealType = MealType.Breakfast },
                new Meal { MealId = 51, Name = "Egg White Omelette with Turkey and Spinach", MealType = MealType.Breakfast },
                new Meal { MealId = 52, Name = "Breakfast Burrito", MealType = MealType.Breakfast },
                new Meal { MealId = 53, Name = "Smoked Salmon on Wholemeal Bread", MealType = MealType.Breakfast },
                new Meal { MealId = 54, Name = "Quinoa Porridge with Berries", MealType = MealType.Breakfast },
                new Meal { MealId = 55, Name = "Grilled Chicken Caesar Salad", MealType = MealType.Lunch },
                new Meal { MealId = 56, Name = "Beef and Broccoli Stir-fry", MealType = MealType.Lunch },
                new Meal { MealId = 57, Name = "Shrimp and Avocado Salad", MealType = MealType.Lunch },
                new Meal { MealId = 58, Name = "Lentil and Vegetable Curry", MealType = MealType.Lunch },
                new Meal { MealId = 59, Name = "Tempeh Sandwich on Wholemeal Bread", MealType = MealType.Lunch },
                new Meal { MealId = 60, Name = "Greek Salad with Chicken", MealType = MealType.Lunch },
                new Meal { MealId = 61, Name = "Stuffed Bell Peppers with Turkey and Quinoa", MealType = MealType.Lunch },
                new Meal { MealId = 62, Name = "Black Bean Burgers", MealType = MealType.Lunch },
                new Meal { MealId = 63, Name = "Pork Chops with Apple and Sweet Potato", MealType = MealType.Dinner },
                new Meal { MealId = 64, Name = "Baked Shrimp with Broccoli", MealType = MealType.Dinner },
                new Meal { MealId = 65, Name = "Chicken and Black Bean Enchiladas", MealType = MealType.Dinner },
                new Meal { MealId = 66, Name = "Vegan Lentil Shepherd's Pie", MealType = MealType.Dinner },
                new Meal { MealId = 67, Name = "Pork and Apple Skewers", MealType = MealType.Dinner },
                new Meal { MealId = 68, Name = "Lemon Herb Chicken with Roasted Potatoes", MealType = MealType.Dinner },
                new Meal { MealId = 69, Name = "Spicy Shrimp with Cauliflower Rice", MealType = MealType.Dinner },
                new Meal { MealId = 70, Name = "Beef and Carrot Stew", MealType = MealType.Dinner },
                new Meal { MealId = 71, Name = "Cucumber Sticks with Hummus", MealType = MealType.AfternoonSnack },
                new Meal { MealId = 72, Name = "A handful of Walnuts", MealType = MealType.AfternoonSnack },
                new Meal { MealId = 73, Name = "Avocado on Wholemeal Bread", MealType = MealType.MorningSnack },
                new Meal { MealId = 74, Name = "Edamame Side", MealType = MealType.AfternoonSnack },
                new Meal { MealId = 75, Name = "A single Pear", MealType = MealType.MorningSnack },
                new Meal { MealId = 76, Name = "Cottage Cheese with Tomato", MealType = MealType.AfternoonSnack },
                new Meal { MealId = 77, Name = "A small bowl of Blueberries", MealType = MealType.MorningSnack },
                new Meal { MealId = 78, Name = "Single Hard-boiled egg", MealType = MealType.MorningSnack },

                // Revised 78 New Varied Meals
                // Low-Calorie / High-Protein (24 Meals)
                new Meal { MealId = 79, Name = "Turkey Slices & Cucumber", MealType = MealType.MorningSnack },
                new Meal { MealId = 80, Name = "Egg White Scramble", MealType = MealType.Breakfast },
                new Meal { MealId = 81, Name = "Grilled Shrimp Skewers", MealType = MealType.Lunch },
                new Meal { MealId = 82, Name = "Cottage Cheese with Chives", MealType = MealType.AfternoonSnack },
                new Meal { MealId = 83, Name = "Steamed White Fish with Lemon", MealType = MealType.Dinner },
                new Meal { MealId = 84, Name = "Chicken Breast Strips", MealType = MealType.Lunch },
                new Meal { MealId = 85, Name = "Plain Greek Yogurt", MealType = MealType.Breakfast },
                new Meal { MealId = 86, Name = "Tuna in Water", MealType = MealType.Lunch },
                new Meal { MealId = 87, Name = "Boiled Shrimp", MealType = MealType.AfternoonSnack },
                new Meal { MealId = 88, Name = "Turkey Jerky", MealType = MealType.MorningSnack },
                new Meal { MealId = 89, Name = "Spinach and Feta Omelette", MealType = MealType.Breakfast },
                new Meal { MealId = 90, Name = "Cod with Asparagus", MealType = MealType.Dinner },
                new Meal { MealId = 91, Name = "Lean Turkey Mince with Broccoli", MealType = MealType.Lunch },
                new Meal { MealId = 92, Name = "Protein Water", MealType = MealType.AfternoonSnack },
                new Meal { MealId = 93, Name = "Seared Scallops", MealType = MealType.Dinner },
                new Meal { MealId = 94, Name = "Bison Steak", MealType = MealType.Dinner },
                new Meal { MealId = 95, Name = "Rabbit Stew", MealType = MealType.Dinner },
                new Meal { MealId = 96, Name = "Venison Steak", MealType = MealType.Dinner },
                new Meal { MealId = 97, Name = "Partridge with Root Vegetables", MealType = MealType.Dinner },
                new Meal { MealId = 98, Name = "Pheasant Breast", MealType = MealType.Dinner },
                new Meal { MealId = 99, Name = "Grilled Halloumi Salad", MealType = MealType.Lunch },
                new Meal { MealId = 100, Name = "Smoked Mackerel Fillet", MealType = MealType.Lunch },
                new Meal { MealId = 101, Name = "Sea Bass with Fennel", MealType = MealType.Dinner },
                new Meal { MealId = 102, Name = "Quark with Berries", MealType = MealType.Breakfast },

                // Balanced Meals (24 Meals)
                new Meal { MealId = 103, Name = "Chicken & Brown Rice Bowl", MealType = MealType.Lunch },
                new Meal { MealId = 104, Name = "Beef Stir-fry with Mixed Veggies", MealType = MealType.Dinner },
                new Meal { MealId = 105, Name = "Baked Cod with Quinoa and Asparagus", MealType = MealType.Dinner },
                new Meal { MealId = 106, Name = "Pork Tenderloin with Roasted Carrots", MealType = MealType.Dinner },
                new Meal { MealId = 107, Name = "Turkey Chili", MealType = MealType.Lunch },
                new Meal { MealId = 108, Name = "Pasta with Chicken and Tomato Sauce", MealType = MealType.Dinner },
                new Meal { MealId = 109, Name = "Shepherd's Pie with Lean Beef", MealType = MealType.Dinner },
                new Meal { MealId = 110, Name = "Salmon Salad Sandwich", MealType = MealType.Lunch },
                new Meal { MealId = 111, Name = "Beef and Barley Soup", MealType = MealType.Lunch },
                new Meal { MealId = 112, Name = "Chicken Fajita Bowl", MealType = MealType.Lunch },
                new Meal { MealId = 113, Name = "Classic Beef Burger on Wholemeal Bun", MealType = MealType.Dinner },
                new Meal { MealId = 114, Name = "Spaghetti Bolognese", MealType = MealType.Dinner },
                new Meal { MealId = 115, Name = "Roast Chicken with Potatoes", MealType = MealType.Dinner },
                new Meal { MealId = 116, Name = "Lamb Chops with Mint Sauce and Peas", MealType = MealType.Dinner },
                new Meal { MealId = 117, Name = "Duck Breast with Orange Glaze", MealType = MealType.Dinner },
                new Meal { MealId = 118, Name = "Moussaka", MealType = MealType.Dinner },
                new Meal { MealId = 119, Name = "Fish and Chips (Baked)", MealType = MealType.Dinner },
                new Meal { MealId = 120, Name = "Chicken Korma", MealType = MealType.Dinner },
                new Meal { MealId = 121, Name = "Beef Rendang", MealType = MealType.Dinner },
                new Meal { MealId = 122, Name = "Paella", MealType = MealType.Dinner },
                new Meal { MealId = 123, Name = "Chicken Tikka Masala", MealType = MealType.Dinner },
                new Meal { MealId = 124, Name = "Sweet and Sour Chicken", MealType = MealType.Dinner },
                new Meal { MealId = 125, Name = "Tuna Pasta Bake", MealType = MealType.Dinner },
                new Meal { MealId = 126, Name = "Sausage and Mash", MealType = MealType.Dinner },

                // High-Calorie / High-Protein (19 Meals)
                new Meal { MealId = 127, Name = "Beef and Pasta Bake", MealType = MealType.Dinner },
                new Meal { MealId = 128, Name = "Salmon with Avocado and Nuts", MealType = MealType.Dinner },
                new Meal { MealId = 129, Name = "Chicken Thighs with Sweet Potato Mash", MealType = MealType.Dinner },
                new Meal { MealId = 130, Name = "Full-Fat Yogurt with Granola and Honey", MealType = MealType.Breakfast },
                new Meal { MealId = 131, Name = "Steak and Eggs", MealType = MealType.Breakfast },
                new Meal { MealId = 132, Name = "Lamb Shoulder with Roasted Root Veg", MealType = MealType.Dinner },
                new Meal { MealId = 133, Name = "Pork Belly with Lentils", MealType = MealType.Dinner },
                new Meal { MealId = 134, Name = "Cheesy Scrambled Eggs with Sausage", MealType = MealType.Breakfast },
                new Meal { MealId = 135, Name = "Weight Gainer Protein Shake", MealType = MealType.AfternoonSnack },
                new Meal { MealId = 136, Name = "Double Cheeseburger", MealType = MealType.Lunch },
                new Meal { MealId = 137, Name = "Mac and Cheese with Bacon", MealType = MealType.Lunch },
                new Meal { MealId = 138, Name = "Peanut Butter & Banana Smoothie", MealType = MealType.Breakfast },
                new Meal { MealId = 139, Name = "Ribeye Steak with Creamed Spinach", MealType = MealType.Dinner },
                new Meal { MealId = 140, Name = "Lasagna", MealType = MealType.Dinner },
                new Meal { MealId = 141, Name = "Carbonara", MealType = MealType.Dinner },
                new Meal { MealId = 142, Name = "Lamb Rogan Josh", MealType = MealType.Dinner },
                new Meal { MealId = 143, Name = "Pulled Pork Bap", MealType = MealType.Lunch },
                new Meal { MealId = 144, Name = "Doner Kebab", MealType = MealType.Dinner },
                new Meal { MealId = 145, Name = "Mixed Grill", MealType = MealType.Dinner },

                // Very-High-Calorie (11 Meals)
                new Meal { MealId = 146, Name = "Pasta with Pesto, Chicken and Nuts", MealType = MealType.Dinner },
                new Meal { MealId = 147, Name = "Beef Chili with Beans and Rice", MealType = MealType.Dinner },
                new Meal { MealId = 148, Name = "Avocado and Salmon Toast", MealType = MealType.Breakfast },
                new Meal { MealId = 149, Name = "Full English Breakfast", MealType = MealType.Breakfast },
                new Meal { MealId = 150, Name = "Pizza", MealType = MealType.Dinner },
                new Meal { MealId = 151, Name = "Gainer Shake with Oats and Peanut Butter", MealType = MealType.AfternoonSnack },
                new Meal { MealId = 152, Name = "Chicken and Chorizo Jambalaya", MealType = MealType.Dinner },
                new Meal { MealId = 153, Name = "Creamy Tuscan Chicken", MealType = MealType.Dinner },
                new Meal { MealId = 154, Name = "Bagel with Cream Cheese and Smoked Salmon", MealType = MealType.Breakfast },
                new Meal { MealId = 155, Name = "Cassoulet", MealType = MealType.Dinner },
                new Meal { MealId = 156, Name = "Feijoada", MealType = MealType.Dinner },

                // 40 New "Large" Meals (1.5x quantity of existing meals)
                // Breakfasts (10)
                new Meal { MealId = 157, Name = "Oatmeal & Fruit Breakfast (Large)", MealType = MealType.Breakfast },
                new Meal { MealId = 158, Name = "Spinach Omelette (Large)", MealType = MealType.Breakfast },
                new Meal { MealId = 159, Name = "Protein Smoothie (Large)", MealType = MealType.Breakfast },
                new Meal { MealId = 160, Name = "Greek Yogurt Parfait (Large)", MealType = MealType.Breakfast },
                new Meal { MealId = 161, Name = "Scrambled Eggs with Spinach and Toast (Large)", MealType = MealType.Breakfast },
                new Meal { MealId = 162, Name = "Overnight Oats with Berries (Large)", MealType = MealType.Breakfast },
                new Meal { MealId = 163, Name = "Tofu Scramble (Large)", MealType = MealType.Breakfast },
                new Meal { MealId = 164, Name = "Breakfast Burrito (Large)", MealType = MealType.Breakfast },
                new Meal { MealId = 165, Name = "Full-Fat Yogurt with Granola and Honey (Large)", MealType = MealType.Breakfast },
                new Meal { MealId = 166, Name = "Steak and Eggs (Large)", MealType = MealType.Breakfast },

                // Lunches (15)
                new Meal { MealId = 167, Name = "Chicken & Quinoa Lunch (Large)", MealType = MealType.Lunch },
                new Meal { MealId = 168, Name = "Tuna Salad (Large)", MealType = MealType.Lunch },
                new Meal { MealId = 169, Name = "Minced Meat with Rice (Large)", MealType = MealType.Lunch },
                new Meal { MealId = 170, Name = "Lentil Soup (Large)", MealType = MealType.Lunch },
                new Meal { MealId = 171, Name = "Black Bean Burrito Bowl (Large)", MealType = MealType.Lunch },
                new Meal { MealId = 172, Name = "Whole Wheat Pasta Primavera (Large)", MealType = MealType.Lunch },
                new Meal { MealId = 173, Name = "Lean Turkey Salad (Large)", MealType = MealType.Lunch },
                new Meal { MealId = 174, Name = "Quinoa Salad with Chickpeas and Veggies (Large)", MealType = MealType.Lunch },
                new Meal { MealId = 175, Name = "Chicken Salad Sandwich (Large)", MealType = MealType.Lunch },
                new Meal { MealId = 176, Name = "Simple Chicken and Rice (Large)", MealType = MealType.Lunch },
                new Meal { MealId = 177, Name = "Grilled Chicken Caesar Salad (Large)", MealType = MealType.Lunch },
                new Meal { MealId = 178, Name = "Beef and Broccoli Stir-fry (Large)", MealType = MealType.Lunch },
                new Meal { MealId = 179, Name = "Greek Salad with Chicken (Large)", MealType = MealType.Lunch },
                new Meal { MealId = 180, Name = "Chicken & Brown Rice Bowl (Large)", MealType = MealType.Lunch },
                new Meal { MealId = 181, Name = "Chicken Fajita Bowl (Large)", MealType = MealType.Lunch },

                // Dinners (15)
                new Meal { MealId = 182, Name = "Salmon & Sweet Potato Dinner (Large)", MealType = MealType.Dinner },
                new Meal { MealId = 183, Name = "Tofu Stir-Fry (Large)", MealType = MealType.Dinner },
                new Meal { MealId = 184, Name = "Pork Loin & Sweet Potato (Large)", MealType = MealType.Dinner },
                new Meal { MealId = 185, Name = "Grilled Beef & Veggies (Large)", MealType = MealType.Dinner },
                new Meal { MealId = 186, Name = "Steamed Salmon & Broccoli (Large)", MealType = MealType.Dinner },
                new Meal { MealId = 187, Name = "Chicken and Vegetable Stir-fry (Large)", MealType = MealType.Dinner },
                new Meal { MealId = 188, Name = "Hearty Beef and Vegetable Stew (Large)", MealType = MealType.Dinner },
                new Meal { MealId = 189, Name = "Turkey Meatballs with Whole Wheat Pasta (Large)", MealType = MealType.Dinner },
                new Meal { MealId = 190, Name = "Baked Salmon with Roasted Potatoes and Carrots (Large)", MealType = MealType.Dinner },
                new Meal { MealId = 191, Name = "Stuffed Bell Peppers with Turkey and Quinoa (Large)", MealType = MealType.Dinner },
                new Meal { MealId = 192, Name = "Lemon Herb Chicken with Roasted Potatoes (Large)", MealType = MealType.Dinner },
                new Meal { MealId = 193, Name = "Beef and Carrot Stew (Large)", MealType = MealType.Dinner },
                new Meal { MealId = 194, Name = "Beef Stir-fry with Mixed Veggies (Large)", MealType = MealType.Dinner },
                new Meal { MealId = 195, Name = "Spaghetti Bolognese (Large)", MealType = MealType.Dinner },
                new Meal { MealId = 196, Name = "Roast Chicken with Potatoes (Large)", MealType = MealType.Dinner }
            );
        }
    }
}
